name: Stylecheck
on:
  push:

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: [ '3.7', '3.8' ]
    name: Stylecheck with Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v1
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - run: pip install -r requirements.txt; black --check .
