name: Run tests and validate codestyle
on:
  push:

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: [ '3.7', '3.8' ]
    name: Test with Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - run: |
            pip install -r requirements.txt
            black --check .
            python tests.py
